-- this script is executed automatically by Spring Boot
DROP TABLE ARTICLE;

CREATE TABLE ARTICLE (ID INT PRIMARY KEY auto_increment, TITLE VARCHAR2(100), CONTENT TEXT, ORIGINALLINK VARCHAR2(100) NULL);